version: '3'
services:
  app:
    build:
      context: .
    command: dlv debug --headless --listen=:2345 --api-version=2 hello.go
    volumes:
      - .:/app
    ports:
      - 2345:2345
    security_opt:
      - seccomp:unconfined
